### ISSUE TITLE
Allow exporting unused functions

### ISSUE THREAD

**Issue by lsund** [faucet-pipeline/faucet-pipeline-js#121]
I would like to be able to export functions, even if they are unused by the bundle as a whole. Reproduction:  With the following  configuration:
```
"use strict";

let templateDir = "./src/main/resources/views";

module.exports = {
    watchDirs: [templateDir],
    js: [{
        source: templateDir + "/index.js",
        target: "./target/classes/dist/views.js",
        jsx: { pragma: "createElement" },
        esnext: true,
        format: "esm",
    }]
};
```

The following is the relevant part of by js bundle:

```
import views from "./manifest";
import Renderer from "complate-stream";

let renderer = new Renderer("<!DOCTYPE html>");

views.forEach(view => {
        renderer.registerView(view);
});

let render = function render(stream, tag, params) {
    renderer.renderView(tag, params, stream, true, null);
    stream.flush();
}
```
Downstream requires that the last thing in  the dist/views.js is exactly that `render` function above. But render is unused by the bundle and is excluded by faucet when creating the `dist/views.js`. In the transpiled file, the function `render` is not present.

I could get around this problem by referring to the function in a hacky way like `console.log(render)` on the line before defining the function. But it would be better to be able to configure the option weather to exclude unused functions.

If you point me to a possible solution, I can also try to implement it.

**Comment by FND** [comment]
This happens due to [tree shaking](https://rollupjs.org/guide/en/#tree-shaking), for which so far there wasn't a reason to make it configurable. In your case, you'll want to export `render`:

```javascript
export default function render(…) {
    …
}
```

```javascript
module.exports = {
    …
    js: [{
        …
        exports: "render",
        …
    }]
};
```

You might also be interested in #97's WIP documentation: https://github.com/faucet-pipeline/faucet-pipeline-js/blob/docs/README.md

HTH.

**Comment by lsund** [comment]
Thanks for the reply and the hint to the documentation. I did export the function, but it also generates the line `export default render` which the caller cannot handle. I'm trying to use the generated views.js with (https://docs.oracle.com/javase/8/docs/jdk/api/nashorn/jdk/nashorn/api/scripting/NashornScriptEngine.html#invokeMethod-java.lang.Object-java.lang.String-java.lang.Object...-)[the java Nashorn Scripting Engine], this is the error message to be specific.

I'm using these technologies for the first time (both the java as well as the javascript side) so it is possible that I can work around it in some other way that I do not yet know. I'll need to have another look at this at some later point. Thanks!

```
failed to evaluate script ('render' in 'filepath') <eval>:509:0 Expected an operand but found export export default render; ^
com.github.complate.ScriptingException: failed to evaluate script ('render' in 'filepath')
<eval>:509:0 Expected an operand but found export
export default render;
```

**Comment by FND** [comment]
Oh, right, I should have pointed out that you'll want `format: "iife"` in that context (or just omit that line, as IIFE is the default): Nashorn doesn't support the modern ESM format.

Let us know if you run into any more trouble; we're happy to help.

**Comment by lsund** [comment]
That indeed works! thanks for the help :) Closing this.
